name: 'TypeScript report'
description: 'GitHub Action to report TypeScript errors in Pull Requests'
author: 'Fernando Silva'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: check-square
  color: blue
inputs:
  githubToken:
    description: 'GitHub token'
  files:
    description: 'Files to check'
